### ISSUE TITLE
Meta Issue: Open Data PVnet

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/open-data-pvnet#5]
The idea is to make sure PVnet is accessible and usable for Open source user and contributors. 

Current problems are lots of the NWP data is private. 

Other context, we are moving over from ocf-datapipes to ocf-datasampler, so I would vote we try to use ocf-datasample at all points. 

Here's a rough list of task lists that need
- [ ] openclimatefix/open-data-pvnet#3
- [ ] openclimatefix/open-data-pvnet#2
- [ ] openclimatefix/open-data-pvnet#1
- [ ] openclimatefix/PVNet#285
- [ ] openclimatefix/PVNet#286
- [ ] openclimatefix/PVNet#287
- [ ] openclimatefix/PVNet#288

If all these steps are complete, then it will be ready to use for different countries and different geographies

**Comment by jcamier** [comment]
@peterdudfield after thinking it over some more, I propose we don't include the architecture overview image in our readme for the time being. Maybe after we have a few more passes at it, we can include it then? However, I am including it here as an artifact we can reference later.
![Image](https://github.com/user-attachments/assets/123de0db-a56a-4c27-b49f-31456b0fc297)

**Comment by peterdudfield** [comment]
Is ti worth putting this on the readme @jcamier ?

**Comment by MAYANK12SHARMA** [comment]
Hi @peterdudfield,

I went through the entire conversation, thank you for that! I’m really interested in contributing to this project and had a couple of ideas I wanted to share for your feedback.

I noticed that there are quite a few README files in the root directory, and I was wondering if organizing them into a subfolder might make the repository structure a bit clearer. Additionally, I saw that the Maintainers.md file doesn’t currently include instructions for setting up environment variables. I’d be happy to add that section to make it easier for new contributors to set up their local environment.

I’d love to hear your thoughts on these suggestions and if you agree please let me know.

Thanks so much!

**Comment by jcamier** [comment]
@MAYANK12SHARMA we created the readme to have a link to getting_started and then getting_started to have links to all the other markdown files. The goal is that if someone reads this on github they can easily click links to get familiar to various aspects of the project. Whatever gaps you find, please feel free to add and create a PR for us to review. Thanks again for your interest! We look forward to collaborating with you.
